### ISSUE TITLE
libVuforia.so could not be found

### ISSUE THREAD

**Issue by dgorbunov** [OpenFTC/OpenRC-Turbo#10]
It seems that libVuforia was removed from filesforDynamicLoad in a recent commit. I'm running a Control Hub and it could not longer boot up the app without the file present in root directory (not FIRST/vision)

**Comment by FROGbots-4634** [comment]
Whooops! I will re-add it now.

**Comment by FROGbots-4634** [comment]
I have re-added the file to the `filesforDynamicLoad` folder. So you should be able to get it up and running for now. Now I need to think about whether I want to migrate the load path to `FIRST/vision` for the Vuforia lib as well, for consistency.

**Comment by dgorbunov** [comment]
The app boots with the new libVuforia.so in FIRST/vision. Is this the expected behavior? Thanks.

**Comment by FROGbots-4634** [comment]
Wait, what? I don't see how that's possible; the vuforia loading code is still looking for it at `/sdcard/FIRST/libVuforia.so`

**Comment by dgorbunov** [comment]
Oh whoops, I was confusing this with libOpenCvNative.so
