### ISSUE TITLE
OnBotJava not working on Stock Build Variant

### ISSUE THREAD

**Issue by AceOfSpades475** [OpenFTC/OpenRC-Turbo#13]
Hello FROGBots!

I have been running into an error where Blocks does work, but when I switch to stock build variant, then the Gradle build gives me the following error. Is there something wrong?

To get to this, I had to add this to the settings.gradle: 

include ':RobotCore', ':Blocks', ':RobotServer', ':FtcRobotController', ':FtcCommon', ':Hardware', ':Inspection', ':TeamCode', ':OpenRC', **':OnBotJava'**

```
Cannot choose between the following variants of project :Blocks:
  - extremeTurboDebugApiElements
  - stockDebugApiElements
  - turboDebugApiElements
All of them match the consumer attributes:
  - Variant 'extremeTurboDebugApiElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'extremeTurboDebug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
      - Found type 'extremeTurbo' but wasn't required.
  - Variant 'stockDebugApiElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'stockDebug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
      - Found type 'stock' but wasn't required.
  - Variant 'turboDebugApiElements':
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'turboDebug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
      - Found type 'turbo' but wasn't required.
```

Thanks!

**Comment by FROGbots-4634** [comment]
> I have been running into an error where Blocks does work, but when I switch to stock build variant, then the Gradle build gives me the following error. Is there something wrong?

Can you provide a screenshot of what your AS window looks like (with the variant pane expanded) after switching to the stock variant?

> To get to this, I had to add this to the settings.gradle:
> include ':RobotCore', ':Blocks', ':RobotServer', ':FtcRobotController', ':FtcCommon', ':Hardware', ':Inspection', ':TeamCode', ':OpenRC', ':OnBotJava'

I'm not entirely clear on what you're trying to say here. What do you mean by `To get to this`?

**Comment by AceOfSpades475** [comment]
Sorry for the confusion - by "to get to this" I meant steps to reproduce the error. Here is what my Android Studio looks like with the build variant:

![Screenshot (131)](https://user-images.githubusercontent.com/74439372/99461833-5bf0db80-28e7-11eb-8d29-7e4c47268d36.png)

Also, I was wondering if there was a way I could enable OnBotJava on turbo mode? It would be very helpful as I am modifying some code in the modules for fun and the stock build uses the default JARS

**Comment by FROGbots-4634** [comment]
You don't need to modify any gradle scripts to use OnBotJava in stock mode. The precompiled AAR file for OnBotJava in stock mode is pulled in as you can see [here](https://github.com/OpenFTC/OpenRC-Turbo/blob/master/FtcRobotController/build.gradle#L50). OnBotJava should function in stock mode just fine without any modifications.

The OnBotJava module is entirely dormant in this repository. It's an artifact of the fact that this repo is based off the git history of [Extracted-RC](https://github.com/OpenFTC/Extracted-RC).

Now regarding your question of:

> Also, I was wondering if there was a way I could enable OnBotJava on turbo mode? It would be very helpful as I am modifying some code in the modules for fun and the stock build uses the default JARS

If you want to play with the **all** the source code for fun (including OBJ), you should use [Extracted-RC](https://github.com/OpenFTC/Extracted-RC). It doesn't have the APK size reductions or competition legal "stock" mode that OpenRC Turbo does, but it doesn't sound like either of those are really an issue for your use case.

**Comment by AceOfSpades475** [comment]
Looks like I got it to work with Extracted-RC. Thank you so much for your help, FROGbots!!
