### ISSUE TITLE
Setup Process in readme.md is not accurate - libVuforia.so should be copied to FIRST instead of FIRST/vision

### ISSUE THREAD

**Issue by pennygao** [OpenFTC/OpenRC-Turbo#15]
Setup Process in readme.md is not accurate - libVuforia.so should be copied to FIRST instead of FIRST/vision, otherwise the app pops up "libVuforia.so was not found. Please copy it to the FIRST folder on the internal storage." then exits.

**Comment by Windwoes** [comment]
Ooops. [I was going to think about whether the vuforia lib should be migrated to the vision directory as well](https://github.com/OpenFTC/OpenRC-Turbo/issues/10#issuecomment-699729095) and then I completely forgot. For the moment, updating the readme is probably easiest.

**Comment by Windwoes** [comment]
Fixed in 7.0A
