### ISSUE TITLE
Expansion Hub Not Recognized

### ISSUE THREAD

**Issue by tatewilhelm** [OpenFTC/OpenRC-Turbo#18]
Our expansion hub wasn't found when we used OpenRC, but when we switched to the bare SDK it worked just fine.

**Comment by NoahAndrews** [comment]
Can you elaborate on "wasn't found"? Was this when you were doing a scan on the configuration screen?

**Comment by averagedolphin** [comment]
Configuration mostly, occasionally when looking at scrcpy we could see "control hub not found on initialization, robot restart required" but when we restarted its would either not show the error anymore, but it couldn't be found in configuration. Or it would go away but still not be available in configuration.

We have tried multiple hubs w latest firmware.

**Comment by Windwoes** [comment]
What happens if you use OpenRC in stock mode?

**Comment by averagedolphin** [comment]
> What happens if you use OpenRC in stock mode?

We were using stock mode

**Comment by Windwoes** [comment]
Wait, so stock mode has the issue you're describing but the official SDK does not?

**Comment by averagedolphin** [comment]
I believe so

**Comment by Windwoes** [comment]
Well that makes literally no sense. Since both the official SDK and stock mode use the same FTC library artifacts from maven.

**Comment by averagedolphin** [comment]
That's weird I'll retry a build Monday, and remove the issue if it was debug, but I thought it was stock

**Comment by NoahAndrews** [comment]
"debug" is opposite of "release", not "stock". It's an unrelated concept.

**Comment by averagedolphin** [comment]
> "debug" is opposite of "release", not "stock". It's an unrelated concept.

I ment I'll remove the issue if I was running the debug variant, not that I'm going to run the debug variant. I thought I was running the stock variant.

**Comment by Windwoes** [comment]
No no no. "Debug" and "release" is totally unrelated to "stock" and "extremeTurbo" / "turbo"

**Comment by averagedolphin** [comment]
> No no no. "Debug" and "release" is totally unrelated to "stock" and "extremeTurbo" / "turbo"

Ahh i confused the names, My bad.
