### ISSUE TITLE
SDK v8.2 Dropped

### ISSUE THREAD

**Issue by matveitolochko** [OpenFTC/OpenRC-Turbo#24]
so https://github.com/FIRST-Tech-Challenge/FtcRobotController/commit/5c8b4c448b2508fd93df7d8e050a324eb7c7dc56 got pushed, and it changed a few things...

**Comment by Windwoes** [comment]
Yep. I just haven't prioritized updating this since it seems like interest has dwindled to almost nothing lately.

**Comment by matveitolochko** [comment]
Got It, might do it myself then
