### ISSUE TITLE
Assets visible in configuration screen

### ISSUE THREAD

**Issue by ajtrowell** [OpenFTC/OpenRC-Turbo#3]
XML files from the FIRST folder are all visible in the phone's robot configuration screen. The consequence is that the asset files are all mixed in with the actual config files on the configuration screen.

Might it be possible to prevent this by putting the assets into a sub-folder?

**Comment by FROGbots-4634** [comment]
Hmm good catch.

**Comment by FROGbots-4634** [comment]
Update: haven't forgotten about this, but working on EasyOpenCV v1.3 at the moment :)

**Comment by FROGbots-4634** [comment]
Fixed in v6.0A, assets are now loaded from `/sdcard/FIRST/vision`
